elice_library/views/comment_view.py
from flask import Blueprint, request, render_template, url_for, flash, session, g, jsonify
from werkzeug.utils import redirect
from models import Book, Comment, User
from app import db
import pytz

bp = Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/delete', methods=['POST'])
def delete():
    comment_id = request.form['comment_id']
    comment = Comment.query.filter_by(comment_id=comment_id).first()

    book_id = comment.book.book_id
    book = Book.query.filter_by(book_id=book_id).first()
    rows = Comment.query.filter_by(book_id=book_id).all()

    len_of_rows = len(rows) - 1
    if len_of_rows != 0:
        rating_sum = 0
        for row in rows:
            rating_sum += row.rating
        rating_sum -= comment.rating
        avg_rating = round(rating_sum / len_of_rows)
        book.rating = avg_rating
    else:
        book.rating = 0

    db.session.delete(comment)
    db.session.commit()

    return jsonify({"message": "success"})


# @bp.route('/update/<int:comment_id>', methods=['GET'])
# def update_try(comment_id):
#     # data = request.get_json()
#     # book_id = request.form['book_id']
#     to_be_updated = Comment.query.filter_by(comment_id=comment_id).first()
#     book_id = to_be_updated.book.book_id

#     comment_list = Comment.query.filter_by(
#         book_id=book_id).order_by(Comment.created_at.desc())
#     book = Book.query.filter_by(book_id=book_id).first()

#     created_times = []
#     for comment in comment_list:
#         created_time = comment.created_at
#         created_times.append(created_time.astimezone(
#             pytz.timezone("Asia/Seoul")))

#     comment_list = comment_list.all()

#     return render_template('books/book_detail.html', book=book, comment_list=comment_list, created_times=created_times, to_be_updated=to_be_updated)


# @bp.route('/update/<int:comment_id>', methods=['POST'])
# def update(comment_id):
#     content = request.form['content']

#     comment = Comment.query.filter_by(comment_id=comment_id).first()
#     book_id = comment.book.book_id

#     comment = Comment.query.filter_by(comment_id=comment_id).first()

#     comment.content = content
#     db.session.commit()

#     return redirect(url_for('main.detail', book_id=book_id))

elice_library/views/main_view.py
from flask import Blueprint, request, render_template, url_for, flash, session, g, jsonify
from werkzeug.utils import redirect
from models import Book, Comment
from app import db

from datetime import datetime
import pytz

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/', methods=['GET'])
def home():
    # search가 있을 경우
    search = request.args.get('search')
    if search is not None:
        search = "%{}%".format(search)
        book_list = Book.query.filter(Book.book_name.like(
            search)).order_by(Book.book_id.asc())

    else:
        book_list = Book.query.order_by(Book.book_id.asc())

    page = request.args.get('page', type=int, default=1)
    book_list = book_list.paginate(page, per_page=8)
    return render_template('books/index.html', book_list=book_list)


@bp.route('/create-comment/<int:book_id>', methods=['POST'])
def create_comment(book_id):
    if g.user is None:
        flash('로그인 후 사용할 수 있습니다.')
        return redirect(url_for('main.detail', book_id=book_id))
    else:
        user_id = session['user_id']
        content = request.form['content']
        try:
            rating = request.form['rating']
        except:
            rating = 0

        if len(content) == 0:
            flash('내용을 입력해 주세요!')
            return redirect(url_for('main.detail', book_id=book_id))

        comment = Comment(user_id=user_id, book_id=book_id,
                          rating=rating, content=content)

        db.session.add(comment)
        db.session.commit()

        # rating update
        rows = Comment.query.filter_by(
            book_id=book_id).all()
        if len(rows) != 0:
            rating_sum = 0
            for row in rows:
                rating_sum += row.rating
            avg_rating = round(rating_sum / len(rows))
            book = Book.query.filter_by(book_id=book_id).first()
            book.rating = avg_rating
            db.session.commit()

        flash('리뷰가 성공적으로 작성되었습니다.')
        return redirect(url_for('main.detail', book_id=book_id))


@bp.route('/detail/<int:book_id>', methods=['GET'])
def detail(book_id):
    # data = request.get_json()
    # book_id = request.form['book_id']
    comment_list = Comment.query.filter_by(
        book_id=book_id).order_by(Comment.comment_id.desc()).all()
    book = Book.query.filter_by(book_id=book_id).first()

    # created_times = []
    # for comment in comment_list:
    #     created_time = comment.created_at
    #     created_times.append(created_time.astimezone(
    #         pytz.timezone("Asia/Seoul")))

    # comment_list = comment_list.all()

    return render_template('books/book_detail.html', book=book, comment_list=comment_list)

elice_library/views/rental_view.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from models import Book, Rental
from app import db
from werkzeug.utils import redirect

from datetime import datetime

bp = Blueprint('rental', __name__, url_prefix='/rental')


@bp.route('/record', methods=['GET'])
def record():
    if g.user is None:
        flash('로그인 후 대여기록을 볼 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        user_id = session['user_id']

        # search가 있을 경우
        search = request.args.get('search')
        if search is not None:
            search = "%{}%".format(search)
            rental_list = Rental.query.join(Book).filter(
                Rental.user_id == user_id, Rental.returned_at != None, Book.book_name.like(search)).order_by(Rental.rented_at.desc())

        else:
            rental_list = Rental.query.filter(
                Rental.user_id == user_id, Rental.returned_at != None).order_by(Rental.rented_at.desc())

        page = request.args.get('page', type=int, default=1)
        rental_list = rental_list.paginate(page, per_page=8)

        return render_template('rental/rental_record.html', rental_list=rental_list)


@bp.route('/<int:book_id>', methods=['POST'])
def rent(book_id):
    if g.user is None:
        flash('로그인 후 대여할 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        book = Book.query.filter_by(book_id=book_id).first()
        user_id = session['user_id']
        if book.stock > 0:
            has_already_rented = Rental.query.filter(
                Rental.user_id == user_id, Rental.book_id == book_id, Rental.rented_at != None, Rental.returned_at == None).first()
            if has_already_rented:
                flash('이미 대여중인 책은 중복 대여가 불가능합니다.')
                return redirect(url_for('main.home'))
            else:
                book.stock -= 1
                rental = Rental(user_id=user_id,
                                book_id=book_id, returned_at=None)
                db.session.add(rental)
                db.session.commit()

                flash('성공적으로 대여 되었습니다.')
                return redirect(url_for('rental.rented_now'))
        else:
            flash('현재 대여 가능한 책이 없습니다.')
            return redirect(url_for('main.home'))


@bp.route('/return', methods=['GET'])
def rented_now():
    if g.user is None:
        flash('로그인 후 반납할 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        user_id = session['user_id']
        rental_list = Rental.query.filter_by(
            user_id=user_id, returned_at=None).order_by(Rental.rented_at.desc())

        img_urls = []
        for rental in rental_list:
            img_urls.append('.' + rental.book.img_url)

        page = request.args.get('page', type=int, default=1)
        rental_list = rental_list.paginate(page, per_page=8)

        return render_template('rental/rented_list.html', rental_list=rental_list, img_urls=img_urls)


@bp.route('/return/<int:book_id>', methods=['POST'])
def return_book(book_id):
    user_id = session['user_id']

    rental_data = Rental.query.filter_by(
        book_id=book_id, user_id=user_id, returned_at=None).first()
    book_data = Book.query.filter_by(book_id=book_id).first()

    rental_data.returned_at = datetime.today()
    book_data.stock += 1

    db.session.commit()

    flash('반납이 완료 되었습니다.')
    return redirect(url_for('rental.rented_now'))

elice_library/templates/books/book_detail.html
{% extends './base.html' %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/book_detail.css') }}" />
{% endblock style %}
<div id="flash">
    {% for message in get_flashed_messages() %}
    <div class="flash alert alert-info">
        
    </div>
    {% endfor %}
</div>
{% block content %}
<div class="detail-container">
    <div class="intro-box">
        <div class="intro-img">
            <img src="{{ url_for('static', filename=book.img_url )}}" alt="{{book.book_name}}" />
        </div>
        <div class="book-detail">
            <table>
                <tr>
                    <td class="index">책이름</td>
                    <td class="explain">{{ book.book_name }}</td>
                </tr>
                <tr>
                    <td class="index">출판사</td>
                    <td class="explain">{{ book.publisher }}</td>
                </tr>
                <tr>
                    <td class="index">저자</td>
                    <td class="explain">{{ book.author }}</td>
                </tr>
                <tr>
                    <td class="index">출간일</td>
                    <td class="explain">{{ book.publicated_at.strftime('%Y-%m-%d') }}</td>
                </tr>
                <tr>
                    <td class="index">페이지수</td>
                    <td class="explain">{{ book.pages }}</td>
                </tr>
                <tr>
                    <td class="index">ISBN 코드</td>
                    <td class="explain">{{ book.isbn }}</td>
                </tr>
            </table>
        </div>
    </div>
    <p class="desc">책 소개</p>
    <div class="desc-box">
        <p>{{book.description}}</p>
    </div>
    <p class="desc">리뷰</p>
    <div class="comment-container">
        {% if comment_list %}
        {% for i in range(comment_list|length) %}
        <div class="comment-box">
            <div class="comment-header">
                <p class="comment-user">{{comment_list[i].user_id}}</p>
                <div class="comment-update-delete">
                    {% if session['user_id'] == comment_list[i].user_id %}
                    <button id="comment-btn" class="comment-delete" data-id="{{ comment_list[i].comment_id }}">
                        삭제
                    </button>
                    {% endif %}
                </div>
            </div>
            <div class="comment-content-box">
                <p class="comment-content">{{comment_list[i].content}}</p>
            </div>
            <div class="comment-footer">
                <p class="comment-date">
                    {{ comment_list[i].created_at.strftime('%Y-%m-%d') }}</p>
                <div id="comment-rating" class="rating-result" data="{{comment_list[i].rating}}">
                    {% for i in range(comment_list[i].rating) %}
                    <span class="fa fa-star checked"></span>
                    {% endfor %}
                    {% for i in range(5 - (comment_list[i].rating)) %}
                    <span class="fa fa-star"></span>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
        {% if g.user %}
        <div class="comment-create">
            <form action="{{ url_for('main.create_comment', book_id=book.book_id)}}" method="post">
                <textarea id='comment-content' class="comment-create-content" rows="3" name="content"
                    placeholder="리뷰를 작성하세요!"></textarea>
                <div class="comment-create-footer">
                    <div class="rating">
                        <input type="radio" name="rating" id="rating-5" value="5">
                        <label for="rating-5"></label>
                        <input type="radio" name="rating" id="rating-4" value="4">
                        <label for="rating-4"></label>
                        <input type="radio" name="rating" id="rating-3" value="3">
                        <label for="rating-3"></label>
                        <input type="radio" name="rating" id="rating-2" value="2">
                        <label for="rating-2"></label>
                        <input type="radio" name="rating" id="rating-1" value="1">
                        <label for="rating-1"></label>
                    </div>
                    <button type="submit" class="create-comment-btn">
                        등록하기
                    </button>
                </div>
            </form>
        </div>
        {% else %}
        <div class="no-reviews">
            <p>책이 어떠셨나요? 리뷰를 남겨주세요!</p>
            <a href="{{ url_for('auth.login') }}">
                <p class="login-for-review">로그인 후 리뷰 남기기
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}
{% block jscontent %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".comment-delete").on('click', function() {
            if(confirm("정말 삭제하시겠습니까?")) {
                $.ajax({
                    url: "{{ url_for('comment.delete') }}",
                    type: 'POST',
                    dataType : 'JSON',
                    data: {
                        'comment_id': $(this).data('id'),
                    },
                    success: function (res) {
                        let msg = res['message']
                        if (msg === 'success') {
                            window.location.reload()
                        } else {
                            alert('오류가 생겼습니다.')
                        }
                    }
                })
            }
        });
    });
</script>
{% endblock jscontent %}

elice_library/templates/books/index.html
{% extends './base.html' %}
{% block content %}
<div class="total-record">
    <div class="search-container">
        <form action="{{ url_for('main.home') }}" method="get">
            <input type="text" placeholder="책을 검색하세요!" name="search">
            <button id="search-btn" type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
</div>
<div class="container">
    {% if book_list %}
        {% for book in book_list.items %}
        <div class="book-container">
            <div class="book">
                <a href="{{ url_for('main.detail', book_id=book.book_id) }}" >
                    <div class="book-img">
                        <img src="{{ url_for('static', filename=book.img_url )}}" alt="{{book.book_name}}" />
                    </div>
                <div class="book-title">
                    <a href="{{ url_for('main.detail', book_id=book.book_id) }}">
                        <h5>{{book.book_name}}</h5>
                    </a>
                </div>
                <div class="book-info">
                    <div class="rating-result" data="{{book.rating}}">
                        {% for i in range(book.rating) %}
                        <span class="fa fa-star checked"></span>
                        {% endfor %}
                        {% for i in range(5 - (book.rating)) %}
                        <span class="fa fa-star"></span>
                        {% endfor %}
                    </div>
                    <p>{{book.stock}}권 남음</p>
                    <form class="btn_rent" action="{{ url_for('rental.rent', book_id=book.book_id) }}"
                        method="post">
                        <button id="btn_rent" type="submit">대여하기</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
    <div class="blank">
        <p>아직 책이 없어요.</p>
    </div>
    {% endif %}
</div>
<nav id="pagination-nav" aria-label="Page navigation example">
    <ul class="pagination">
        {% if book_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ book_list.prev_num }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">이전</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tab-index="-1" aria-disabled="true" href="#">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">이전</span>
            </a>
        </li>
        {% endif %}
        {% for page_num in book_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != book_list.page %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                {% else %}
                   <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ page_num }}</a>
                    </li> 
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if book_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ book_list.next_num }}">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">다음</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">다음</span>
                </a>
            </li>
        {% endif %}
        </li>
    </ul>
</nav>
{% endblock content %}