elice_library/views/rental_view.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from models import Book, Rental
from app import db
from werkzeug.utils import redirect

from datetime import datetime

bp = Blueprint('rental', __name__, url_prefix='/rental')


@bp.route('/record', methods=['GET'])
def record():
    if g.user is None:
        flash('로그인 후 대여기록을 볼 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        user_id = session['user_id']

        # search가 있을 경우
        search = request.args.get('search')
        if search is not None:
            search = "%{}%".format(search)
            rental_list = Rental.query.join(Book).filter(
                Rental.user_id == user_id, Rental.returned_at != None, Book.book_name.like(search)).order_by(Rental.rented_at.desc())

        else:
            rental_list = Rental.query.filter(
                Rental.user_id == user_id, Rental.returned_at != None).order_by(Rental.rented_at.desc())

        page = request.args.get('page', type=int, default=1)
        rental_list = rental_list.paginate(page, per_page=8)

        return render_template('rental/rental_record.html', rental_list=rental_list)


@bp.route('/<int:book_id>', methods=['POST'])
def rent(book_id):
    if g.user is None:
        flash('로그인 후 대여할 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        book = Book.query.filter_by(book_id=book_id).first()
        user_id = session['user_id']
        if book.stock > 0:
            has_already_rented = Rental.query.filter(
                Rental.user_id == user_id, Rental.book_id == book_id, Rental.rented_at != None, Rental.returned_at == None).first()
            if has_already_rented:
                flash('이미 대여중인 책은 중복 대여가 불가능합니다.')
                return redirect(url_for('main.home'))
            else:
                book.stock -= 1
                rental = Rental(user_id=user_id,
                                book_id=book_id, returned_at=None)
                db.session.add(rental)
                db.session.commit()

                flash('성공적으로 대여 되었습니다.')
                return redirect(url_for('rental.rented_now'))
        else:
            flash('현재 대여 가능한 책이 없습니다.')
            return redirect(url_for('main.home'))


@bp.route('/return', methods=['GET'])
def rented_now():
    if g.user is None:
        flash('로그인 후 반납할 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        user_id = session['user_id']
        rental_list = Rental.query.filter_by(
            user_id=user_id, returned_at=None).order_by(Rental.rented_at.desc())

        img_urls = []
        for rental in rental_list:
            img_urls.append('.' + rental.book.img_url)

        page = request.args.get('page', type=int, default=1)
        rental_list = rental_list.paginate(page, per_page=8)

        return render_template('rental/rented_list.html', rental_list=rental_list, img_urls=img_urls)


@bp.route('/return/<int:book_id>', methods=['POST'])
def return_book(book_id):
    user_id = session['user_id']

    rental_data = Rental.query.filter_by(
        book_id=book_id, user_id=user_id, returned_at=None).first()
    book_data = Book.query.filter_by(book_id=book_id).first()

    rental_data.returned_at = datetime.today()
    book_data.stock += 1

    db.session.commit()

    flash('반납이 완료 되었습니다.')
    return redirect(url_for('rental.rented_now'))

elice_library/templates/rental/rental_record.html
{% extends './base.html' %}
{% block content %}
<div class="total-record">
    <p>총 {{ rental_list.total }}권의 대여기록이 있습니다.</p>
  <div class="search-container">
      <form action="{{ url_for('rental.record') }}" method="get">
          <input type="text" placeholder="책을 검색하세요!" name="search">
          <button id="search-btn" type="submit"><i class="fa fa-search"></i></button>
      </form>
  </div>
</div>
<div class="container">
    {% if rental_list %}     
        {% for i in range(rental_list.items|length) %}
            <div class="book-container">
                <div class="book">
                    <a href="{{ url_for('main.detail', book_id=rental_list.items[i].book_id) }}">
                        <div class="book-img">
                            <img src="{{ url_for('static', filename=rental_list.items[i].book.img_url )}}"
                                alt="{{rental_list.items[i].book_name}}" />
                        </div>
                    </a>
                    <div class="book-title">
                        <a href="{{ url_for('main.detail', book_id=rental_list.items[i].book_id) }}">
                            <h5>{{rental_list.items[i].book.book_name}}</h5>
                        </a>
                    </div>
                    <div class="book-info">
                        <div class="rating-result" data="{{rental_list.items[i].book.rating}}">
                            {% for j in range(rental_list.items[i].book.rating) %}
                            <span class="fa fa-star checked"></span>
                            {% endfor %}
                            {% for j in range(5 - (rental_list.items[i].book.rating)) %}
                            <span class="fa fa-star"></span>
                            {% endfor %}
                        </div>

                        <p>
                        {{rental_list.items[i].rented_at.strftime('%Y-%m-%d')}}<br>
                        ~<br>
                        {{rental_list.items[i].returned_at.strftime('%Y-%m-%d')}}
                        </p>
                        
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p class="no-record">아직 대여한 책이 없어요.</p>
    {% endif %}
</div>
<nav id="pagination-nav" aria-label="Page navigation example">
    <ul class="pagination">
        {% if rental_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ rental_list.prev_num }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">이전</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tab-index="-1" aria-disabled="true" href="#">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">이전</span>
            </a>
        </li>
        {% endif %}
        {% for page_num in rental_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != rental_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if rental_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ rental_list.next_num }}">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">다음</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">다음</span>
            </a>
        </li>
        {% endif %}
        </li>
    </ul>
</nav>

{% endblock content %}

elice_library/templates/rental/rented_list.html
{% extends './base.html' %}
{% block content %}
<div class="total-record">
    <p>총 {{ rental_list.total }}권의 대여내역이 있습니다.</p>
</div>
<div class="container">
    {% if rental_list %}
        {% for i in range(rental_list.items|length) %}
            <div class="book-container">
                <div class="book">
                    <a href="{{ url_for('main.detail', book_id=rental_list.items[i].book_id) }}">
                        <div class="book-img">
                            <img src="{{ url_for('static', filename=rental_list.items[i].book.img_url )}}"
                                alt="{{rental_list.items[i].book_name}}" />
                        </div>
                    </a>
                    <div class="book-title">
                        <a href="{{ url_for('main.detail', book_id=rental_list.items[i].book_id) }}">
                            <h5>{{rental_list.items[i].book.book_name}}</h5>
                        </a>
                    </div>
                    <div class="book-info">
                        <div class="rating-result" data="{{rental_list.items[i].book.rating}}">
                            {% for j in range(rental_list.items[i].book.rating) %}
                            <span class="fa fa-star checked"></span>
                            {% endfor %}
                            {% for j in range(5 - (rental_list.items[i].book.rating)) %}
                            <span class="fa fa-star"></span>
                            {% endfor %}
                        </div>
                        <p>{{rental_list.items[i].rented_at.strftime('%Y-%m-%d')}}</p>
                        <form class="return-btn" action="{{ url_for('rental.return_book', book_id=rental_list.items[i].book.book_id) }}" method="post">
                            <button id="return-btn" type="submit">반납하기</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>아직 대여한 책이 없어요.</p>
    {% endif %}
</div>
<nav id="pagination-nav" aria-label="Page navigation example">
    <ul class="pagination">
        {% if rental_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ rental_list.prev_num }}">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">이전</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tab-index="-1" aria-disabled="true" href="#">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">이전</span>
            </a>
        </li>
        {% endif %}
        {% for page_num in rental_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != rental_list.page %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% if rental_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ rental_list.next_num }}">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">다음</span>
            </a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">다음</span>
            </a>
        </li>
        {% endif %}
        </li>
    </ul>
</nav>
{% endblock content %}