elice_library/views/auth_view.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from werkzeug.utils import redirect
from bcrypt import checkpw, hashpw, gensalt
from app import db
from models import User

from authentication import user_id_validate, signup_pw_validate, name_validate

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)


@bp.route('/login', methods=['GET'])
def login_try():
    return render_template('auth/login.html')


@bp.route('/login', methods=['POST'])
def login():
    user_id = request.form['user_id']
    user_password = request.form['user_password']

    user_data = User.query.filter_by(user_id=user_id).first()

    # validators 실행
    if not user_data:
        flash('아이디를 다시 확인해 주세요.')
        # return redirect(url_for('auth.login_try'))
        return render_template('auth/login.html', user_password=user_password, user_id=user_id)

    elif len(user_password) < 8:
        flash('비밀번호는 8자리 이상 입력하세요.')
        # return redirect(url_for('auth.login_try'))
        return render_template('auth/login.html', user_password=user_password, user_id=user_id)

    elif not checkpw(user_password.encode('utf-8'), user_data.user_password.encode('utf-8')):
        flash('비밀번호가 일치하지 않습니다.')
        # return redirect(url_for('auth.login_try'))
        return render_template('auth/login.html', user_password=user_password, user_id=user_id)

    else:
        session.clear()
        session['user_id'] = user_id
        flash(f'{user_data.user_name}님 안녕하세요!')
        return redirect(url_for('main.home'))


@bp.route('/signup', methods=['GET'])
def signup_try():
    return render_template('auth/signup.html')


@bp.route('/signup', methods=['POST'])
def signup():
    user_id = request.form['user_id']
    user_password = request.form['user_password']
    user_password_check = request.form['user_password_check']
    user_name = request.form['user_name']

    user_data = User.query.filter_by(user_id=user_id).first()

    # 아이디 validator 실행
    if not user_id_validate(user_id):
        flash('아이디는 이메일 형식으로 입력하세요.')
        # return redirect(url_for('auth.signup_try'))
        return render_template('auth/signup.html', user_id=user_id, user_password=user_password, user_password_check=user_password_check, user_name=user_name)

    elif not signup_pw_validate(user_password):
        flash('비밀번호는 영문, 숫자, 특수문자 중 2종류 이상을 조합하여 최소 10자리 이상 또는 3종류 이상을 조합하여 최소 8자리 이상의 길이로 구성해야 합니다.')
        # return redirect(url_for('auth.signup_try'))
        return render_template('auth/signup.html', user_id=user_id, user_password=user_password, user_password_check=user_password_check, user_name=user_name)

    elif not name_validate(user_name):
        flash('이름은 영문 또는 한글로 입력하세요.')
        # return redirect(url_for('auth.signup_try'))
        return render_template('auth/signup.html', user_id=user_id, user_password=user_password, user_password_check=user_password_check, user_name=user_name)

    else:
        # 아이디 중복 확인 후 회원가입 시작
        if not user_data:
            if user_password != user_password_check:
                flash('비밀번호가 일치하지 않습니다.')
                # return redirect(url_for('auth.signup_try'))
                return render_template('auth/signup.html', user_id=user_id, user_password=user_password, user_password_check=user_password_check, user_name=user_name)

            hashed_password = hashpw(
                user_password.encode('utf-8'), gensalt())

            new_user = User(user_id=user_id,
                            user_password=hashed_password, user_name=user_name)
            db.session.add(new_user)
            db.session.commit()

            flash('성공적으로 가입 되었습니다!')
            return redirect(url_for('auth.login'))
        else:
            flash('이미 존재하는 아이디입니다. 다시 입력해 주세요.')
            # return redirect(url_for('auth.signup_try'))
            return render_template('auth/signup.html', user_id=user_id, user_password=user_password, user_password_check=user_password_check, user_name=user_name)


@bp.route('/logout', methods=['GET'])
def logout():
    session.clear()
    flash('로그아웃 되었습니다.')
    return redirect(url_for('main.home'))

elice_library/views/rental_view.py
from flask import Blueprint, render_template, request, url_for, flash, session, g
from models import Book, Rental
from app import db
from werkzeug.utils import redirect

from datetime import datetime

bp = Blueprint('rental', __name__, url_prefix='/rental')


@bp.route('/record', methods=['GET'])
def record():
    if g.user is None:
        flash('로그인 후 대여기록을 볼 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        user_id = session['user_id']

        # search가 있을 경우
        search = request.args.get('search')
        if search is not None:
            search = "%{}%".format(search)
            rental_list = Rental.query.join(Book).filter(
                Rental.user_id == user_id, Rental.returned_at != None, Book.book_name.like(search)).order_by(Rental.rented_at.desc())

        else:
            rental_list = Rental.query.filter(
                Rental.user_id == user_id, Rental.returned_at != None).order_by(Rental.rented_at.desc())

        page = request.args.get('page', type=int, default=1)
        rental_list = rental_list.paginate(page, per_page=8)

        return render_template('rental/rental_record.html', rental_list=rental_list)


@bp.route('/<int:book_id>', methods=['POST'])
def rent(book_id):
    if g.user is None:
        flash('로그인 후 대여할 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        book = Book.query.filter_by(book_id=book_id).first()
        user_id = session['user_id']
        if book.stock > 0:
            has_already_rented = Rental.query.filter(
                Rental.user_id == user_id, Rental.book_id == book_id, Rental.rented_at != None, Rental.returned_at == None).first()
            if has_already_rented:
                flash('이미 대여중인 책은 중복 대여가 불가능합니다.')
                return redirect(url_for('main.home'))
            else:
                book.stock -= 1
                rental = Rental(user_id=user_id,
                                book_id=book_id, returned_at=None)
                db.session.add(rental)
                db.session.commit()

                flash('성공적으로 대여 되었습니다.')
                return redirect(url_for('rental.rented_now'))
        else:
            flash('현재 대여 가능한 책이 없습니다.')
            return redirect(url_for('main.home'))


@bp.route('/return', methods=['GET'])
def rented_now():
    if g.user is None:
        flash('로그인 후 반납할 수 있습니다.')
        return redirect(url_for('main.home'))
    else:
        user_id = session['user_id']
        rental_list = Rental.query.filter_by(
            user_id=user_id, returned_at=None).order_by(Rental.rented_at.desc())

        img_urls = []
        for rental in rental_list:
            img_urls.append('.' + rental.book.img_url)

        page = request.args.get('page', type=int, default=1)
        rental_list = rental_list.paginate(page, per_page=8)

        return render_template('rental/rented_list.html', rental_list=rental_list, img_urls=img_urls)


@bp.route('/return/<int:book_id>', methods=['POST'])
def return_book(book_id):
    user_id = session['user_id']

    rental_data = Rental.query.filter_by(
        book_id=book_id, user_id=user_id, returned_at=None).first()
    book_data = Book.query.filter_by(book_id=book_id).first()

    rental_data.returned_at = datetime.today()
    book_data.stock += 1

    db.session.commit()

    flash('반납이 완료 되었습니다.')
    return redirect(url_for('rental.rented_now'))

elice_library/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="icon" type="image/png" sizes="32x32"
        href="{{ url_for('static', filename='images/favicon-32x32.png')}}" />
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block style %}{% endblock style %}
    <title>레이서 도서관</title>
</head>

<body>
    <header>
        <nav id="header-nav" class="navbar">
            <ul id="nav-title" class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-logo avbar-brand" href="{{ url_for('main.home')}}">레이서 도서관</a>
                </li>
            </ul>
            <ul id="nav-right">
                {% if g.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('rental.record') }}">대여기록</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout')}}">로그아웃</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('rental.rented_now') }}">
                        <button type="button" class="btn_return">
                            반납하기
                        </button>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
                </li>
                {% endif %}
            </ul>
            <div class="hamburger">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </div>
        </nav>
    </header>
    <div id="flash" >
        {% for message in get_flashed_messages() %}
        <div class="flash alert alert-success">
            {{message}}
        </div>
        {% endfor %}
    </div>
    <div id="content">
        {% block content %}{% endblock content %}
    </div>
    <div id="footer">
        <div class="footer">
            <p id="admin-redirect"><a href="{{ url_for('admin.login_try')}}">관리자 페이지</a></p>
            <p>레이서 도서관</p>
        </div>
    </div>
    {% block jscontent %}
    {% endblock jscontent %}
    <script type="text/javascript">
        const hamburger = document.querySelector(".hamburger");
        const navMenu = document.querySelector("#nav-right");

        hamburger.addEventListener("click", mobileMenu);

        function mobileMenu() {
            hamburger.classList.toggle("active");
            navMenu.classList.toggle("active");
        }

        const navLink = document.querySelectorAll(".nav-link");

        navLink.forEach(n => n.addEventListener("click", closeMenu));

        function closeMenu() {
            hamburger.classList.remove("active");
            navMenu.classList.remove("active");
        }
    </script>
</body>
</html>

elice_library/templates/login.html
{% extends './base.html' %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.scss') }}" />
{% endblock style %}
{% block content %}
  <div class="wrapper">
      <form class="form-signin">
          <h2 class="form-signin-heading">로그인 </h2>
          <input type="text" class="form-control" name="username" placeholder="Email Address" required=""
              autofocus="" />
          <input type="password" class="form-control" name="password" placeholder="Password" required="" />
          <label class="checkbox">
              <input type="checkbox" value="remember-me" id="rememberMe" name="rememberMe"> Remember me
          </label>
          <button class="btn btn-lg btn-primary btn-block" type="submit">로그인</button>
      </form>
  </div>
{% endblock content %}

elice_library/templates/signup.html
{% extends './base.html' %}
{% block style %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='signup.scss') }}" />
{% endblock style %}
{% block script %}
    <script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
{% endblock script %}
{% block content %}
<!-- Signup -->
<div id="#signup">
    <div class="signup">
        <h1>Sign up</h1>
        <form class="signup-form" action="{{ url_for('auth.signup')}}" method="post">
            <div class="form-group">
                <label for="signup-email">아이디</label>
                <input type="email" id="signup-email" class="form-control" placeholder="elice@elice.com"
                    value="{{ signup_form.user_id.data or '' }}" />
            </div>
            <div class="form-group">
                <label for="signup-name">이름</label>
                <input type="text" id="signup-name" class="form-control" placeholder="이름을 입력하세요."
                    value="{{ signup_form.user_name.data or '' }}" />
            </div>
            <div class="form-group">
                <label for="signup-password">비밀번호</label>
                <input type="password" id="signup-password" class="form-control" placeholder="비밀번호를 입력하세요."
                    value="{{ signup_form.user_password.data or '' }}" />
                <div class="reveal-password">
                    <svg class="icon">
                        <use xlink:href="#reveal-icon"></use>
                    </svg>
                </div>
                <div id="password-suggestion" class="suggestion"></div>
            </div>
            <div class="form-group">
                <label for="signup-password">비밀번호 확인</label>
                <input type="password" id="signup-password" class="form-control" placeholder="비밀번호를 다시 한 번 입력하세요."
                    value="{{ signup_form.user_password2.data or '' }}" />
                <div class="reveal-password">
                    <svg class="icon">
                        <use xlink:href="#reveal-icon"></use>
                    </svg>
                </div>
                <div id="password-suggestion" class="suggestion"></div>
            </div>
            <button class="signup_btn form-submit" type="submit">Sign up</button>
        </form>
    </div>
    <!-- /Signup -->

    <!-- SVG -->
    <svg xmlns="http://www.w3.org/2000/svg" width="0" height="0" display="none">
        <symbol id="reveal-icon" viewBox="0 0 932.15 932.15">
            <g>
                <path
                    d="M466.075,161.525c-205.6,0-382.8,121.2-464.2,296.1c-2.5,5.3-2.5,11.5,0,16.9c81.4,174.899,258.601,296.1,464.2,296.1   s382.8-121.2,464.2-296.1c2.5-5.3,2.5-11.5,0-16.9C848.875,282.725,671.675,161.525,466.075,161.525z M466.075,676.226   c-116.1,0-210.1-94.101-210.1-210.101c0-116.1,94.1-210.1,210.1-210.1c116.1,0,210.1,94.1,210.1,210.1   S582.075,676.226,466.075,676.226z" />
                <circle cx="466.075" cy="466.025" r="134.5" />
            </g>
        </symbol>
    </svg>
    <!-- /SVG -->
</div>
{% endblock content %}

{% block jscontent %}
<script>
/*------------------------------
Floating Labels & Check Inputs
------------------------------*/
function floatingLabels() {
var $formControl = $('.form-control');

$formControl.each(function() {
var $t = $(this),
$p = $t.parents('.form-group');

$t.on('keyup change', function() {
if ($(this).val().length > 0) {
$p.addClass('filled');
} else {
$p.removeClass('filled');
}
}).on('focus', function() {
$p.addClass('focus');
}).on('blur', function() {
$p.removeClass('focus');
if ($t.val().length <= 1) { $p.addClass('error'); } else { $p.removeClass('error'); } }); });
    } /*----------------------- Reveal & Check Password -----------------------*/ function revealPassword() { var
    $reveal=$('.reveal-password'), $password=$('#signup-password'), $pwdSuggestion=$('#password-suggestion');
    $password.on('keyup change', function() { var $t=$(this), $p=$t.parents('.form-group'), val=$t.val(),
    result=zxcvbn(val, userInputs=[]); if (val.length> 0) {
    $reveal.show();
    $pwdSuggestion.show();

    if (parseInt(result.score) > 2) {
    $pwdSuggestion.html('');
    $p.removeClass('error');
    } else {
    if (result.feedback.warning == '') {
    result.feedback.warning = 'Your password is too short';
    }
    $p.addClass('error');
    $pwdSuggestion.html(result.feedback.warning + '. ' + result.feedback.suggestions.join(' '));
    }
    } else {
    $pwdSuggestion.hide();
    }

    });

    $reveal.click(function() {
    var $t = $(this),
    $p = $t.parents('.form-group');

    $t.toggleClass('active');
    $p.toggleClass('focus');

    var type = ($(this).is('.active')) ? 'text' : 'password';
    $password.attr('type', type);
    });
    }

    /*-----------------
    Email Suggestion
    -----------------*/
    function emailSuggestion() {
    var domains = 'yahoo.com outlook.com google.com hotmail.com inbox.com gmail.com me.com aol.com mac.com lycos.com
    live.com comcast.net googlemail.com msn.com hotmail.co.uk yahoo.co.uk facebook.com verizon.net sbcglobal.net att.net
    gmx.com mail.com'.split(' '),
    topLevelDomains = 'co.uk com net org info edu gov mil'.split(' '),
    $email = $('#signup-email'),
    $suggestion = $('#email-suggestion'),
    $suggestedEmail = $('#suggested-email');

    $email.on('blur', function() {
    var $t = $(this),
    $p = $t.parents('.form-group');

    // check if it's an email
    var pattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/i;
    if (pattern.test($t.val()) == false) {
    $p.addClass('error');
    } else {
    $p.removeClass('error');
    }

    $t.mailcheck({
    domains: domains,
    topLevelDomains: topLevelDomains,
    suggested: function(element, suggestion) {
    $suggestion.slideDown(300);
    $suggestedEmail.html('<a id="suggested-email"><span class="address">' + suggestion.address + '</span>@<span
            class="domain">' + suggestion.domain + '</span></a>');
    }
    });
    });

    // recover
    $suggestedEmail.click(function() {
    $email.val($(this).text());
    $suggestion.slideUp(300);
    });
    }

    /*--------
    DOC READY
    ----------*/
    $(function() {
    floatingLabels();
    revealPassword();
    emailSuggestion();
    });
</script>
{% endblock jscontent %}